# We use the Portable Encapsulated Projects (PEP) standard
# See more on https://pep.databio.org/

pep_version: 2.0.0
# path to the sample table relative to the config file
sample_table: "sample_table.csv"
